import ButtonLink from "@/components/button/ButtonLink";
import InputText from "@/components/input/inputText";
import InputRadio from "@/components/input/InputRadio";
import InputCheckBox from "@/components/input/InputCheckbox";

export const metadata = {
    title: 'subpage title',
    description: 'Generated by Next.js',
  }
  
export default function Subpage() {
    return (<>
        <div className="subpage py-[5rem]">
            <div className="subpage__inner">
                <div className="layout space-y-[4rem]">    
                    <section className="subpage__section">
                        <h2 className="head2 mb-[2rem]">Button</h2>
                        <div className="subpage__cont">
                            <ButtonLink 
                                text={'My Button'} 
                                href={'www.google.com'} /> 
                        </div>
                    </section>
                    <section className="subpage__section">
                        <h2 className="head2 mb-[2rem]">Input Text</h2>
                        <div className="subpage__cont">
                            <InputText placeholder={'Enter Text'} /> 
                        </div>
                    </section>
                    <section className="subpage__section">
                        <h2 className="head2 mb-[2rem]">Input Radio</h2>
                        <div className="subpage__cont">
                            <InputRadio choices={['Rad-choice1', 'Rad-choice2', 'Rad-choice3']} />
                        </div>
                    </section>
                    <section className="subpage__section">
                        <h2 className="head2 mb-[2rem]">Input Checkbox</h2>
                        <div className="subpage__cont">
                            <InputCheckBox choices={['Check-choice1', 'Check-choice2', 'Check-choice3']} />
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </>);
}