import Nav from "@/components/nav/nav";
import Footer from "@/components/footer/footer";
import Header from "@/components/header/header";

import '../stylesheets/css/style.css';

export const metadata = {
  title: 'GERALD NEXT BEYBE',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/>
        <Nav/>
          {children}
        <Footer/>
      </body>
         
    </html>
  )
}
