import CrudForm from "./components/CrudForm";
import CrudList from "./components/CrudList";

export const metadata = {
    title: 'Welcome to CRUD',
    description: 'Generated by Next.js',
}

export default async function Crud() {
    return (<>
        <div className="layout py-[5rem]">
            <h2 className="head2 text-center">Welcome to CRUD</h2>
            <h4 className="head4 text-center mt-[1rem]">This is a sample CRUD App</h4>
            <CrudForm />
            <CrudList />
        </div>
    </>);
}